sudo: required
services:
  - docker

before_install:
  - docker build -t ronny10/docker-react -f Dockerfile.dev .

script:
  - docker run ronny10/docker-react npm run test -- --coverage
# deploy:
# provider: elasticbeanstalk
# region: from link
# app: Name of the app
# env: your environment
# bucket_name:
# bucket_path: same as name of the app
# on:
  # branch: master
# access_key_id: $AWS_ACCESS_KEY
# secret_access_key:
  # secure:"$AWS_SECRET_KEY"

